"""cria tabela processos_licitatorios

Revision ID: 2630e675dac2
Revises: 639bb8556018
Create Date: 2026-09-09 18:14:14.828354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2630e675dac2'
down_revision: Union[str, Sequence[str], None] = '639bb8556018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processos_licitatorios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orgao', sa.String(length=255), nullable=False),
    sa.Column('numero_pregao', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cidade', sa.String(length=120), nullable=False),
    sa.Column('data_certame', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modalidade', sa.Enum('PRESENCIAL', 'ELETRONICO', 'CONCORRENCIA', 'DISPENSA', 'COMPRA_DIRETA', name='modalidade_pregao'), nullable=False),
    sa.Column('portal', sa.Enum('COMPRASGOV', 'LICITANET', 'PORTAL_COMPRAS_PUBLICAS', 'BLL', 'LICITACOES_E', 'OUTROS', name='portal_pregao'), nullable=False),
    sa.Column('portal_outro', sa.String(length=120), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('AGUARDANDO_DECISAO', 'EM_ANDAMENTO', 'SUSPENSO', 'ADIADO', 'EM_DILIGENCIA', 'CANCELADO', 'FINALIZADO', name='status_processo'), nullable=False),
    sa.Column('data_hora_retorno', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_diligencia', sa.Text(), nullable=True),
    sa.Column('criado_por_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processos_licitatorios')
    # ### end Alembic commands ###
