import enum


class Perfil(str, enum.Enum):
    ADMIN = "ADMIN"
    USER = "USER"


class StatusProcesso(str, enum.Enum):
    AGUARDANDO_DECISAO = "AGUARDANDO_DECISAO"
    EM_ANDAMENTO = "EM_ANDAMENTO"
    SUSPENSO = "SUSPENSO"
    ADIADO = "ADIADO"
    EM_DILIGENCIA = "EM_DILIGENCIA"
    CANCELADO = "CANCELADO"
    FINALIZADO = "FINALIZADO"


class Modalidade(str, enum.Enum):
    PRESENCIAL = "PRESENCIAL"
    ELETRONICO = "ELETRONICO"
    CONCORRENCIA = "CONCORRENCIA"
    DISPENSA = "DISPENSA"
    COMPRA_DIRETA = "COMPRA_DIRETA"


class Portal(str, enum.Enum):
    COMPRASGOV = "COMPRASGOV"
    LICITANET = "LICITANET"
    PORTAL_COMPRAS_PUBLICAS = "PORTAL_COMPRAS_PUBLICAS"
    BLL = "BLL"
    LICITACOES_E = "LICITACOES_E"
    OUTROS = "OUTROS"